name: CI

on:
  - push
  - pull_request

jobs:
  # Run the test suite and linters
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Run linters
        run: npm run lint
      - name: Run tests
        run: npm run test

  # Publish the package to NPM if needed (master branch only)
  publish:
    runs-on: ubuntu-18.04
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Setup NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
      - name: Publish semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
